export type EvidenceType = 'image' | 'video' | 'audio' | 'document';

export type EvidenceStatus = 'new' | 'analyzing' | 'analyzed-pending-review' | 'analyzed' | 'analyzed-needs-manual-tagging' | 'error';
export type EmployeeStatus = 'new' | 'researching' | 'ready' | 'error';

export interface Employee {
  id: string;
  name: string;
  details: string; // User-provided details
  referenceUrl?: string;
  referenceImage?: {
    base64: string;
    mimeType: string;
  };
  aiEnhancedDetails?: string; // Details generated by AI research
  status: EmployeeStatus;
  // Disk persistence metadata (optional)
  profileJsonPath?: string; // app/data/profiles/<Name>.profile.json
  referenceImagePath?: string; // app/data/profiles/<Name>.reference.<ext>
}

export interface TimelineEvent {
    timestamp: string;
    description: string;
    subjects: string[]; // Names of people involved
}

export interface CrossReference {
    fileName: string;
    observation: string;
}

export interface RecognizedEmployee {
    name: string;
    timestamp: string;
    confidence: number; // Score from 0-100
}

export interface AnalysisResult {
  summary: string;
  severityScore: number; // Score from 1-10
  keyObservations: {
    timestamp: string;
    description: string;
  }[];
  emotionalAnalysis: {
    emotion: string;
    evidence: string;
  }[];
  recognizedEmployees: RecognizedEmployee[];
  potentialViolations: string[];
  fullTranscript: string;
  // New fields for advanced analysis
  newFindingsSummary: string; // What's new compared to previous evidence
  timelineEvents: TimelineEvent[];
  crossReferences: CrossReference[];
  confidenceScore: number; // 1-100%
  childrenDetected: boolean; // AI's finding on whether children are present
}

export interface EvidenceFile {
  id: string;
  name: string;
  type: EvidenceType;
  url?: string; // Object URL for preview, not persisted
  file?: File; // The actual file object, not persisted
  status: EvidenceStatus;
  hash?: string;
  analysis?: AnalysisResult;
  // New fields for context
  location?: string;
  recognitionVerified?: boolean;
  storedFileName?: string; // Actual file name stored on disk (may include version suffix)
  storedFilePath?: string; // Relative path inside app/data
  analysisDocuments?: string[]; // Relative paths to generated analysis documents
}

export interface ChatMessage {
  id:string;
  role: 'user' | 'model' | 'system';
  content: string;
  isLoading?: boolean;
}

// Types for Relationship Map Feature
export interface InteractionDetail {
  file: string;
  timestamp: string;
  description: string;
}

export interface RelationshipMapNode {
  id: string; // Person's name
}

export type InteractionSentiment = 'positive' | 'negative' | 'neutral' | 'mixed';

export interface RelationshipMapLink {
  source: string; // Person's name
  target: string; // Person's name
  value: number; // Number of interactions
  summary: string;
  interactions: InteractionDetail[];
  sentiment: InteractionSentiment;
}

export interface RelationshipMapData {
  nodes: RelationshipMapNode[];
  links: RelationshipMapLink[];
  overallSummary: string;
}

// Additional witness testimony support
export interface WitnessTestimony {
  id: string;
  name: string; // e.g., Juliana
  role: string; // e.g., Former Employee
  testimony: string;
  referenceUrl?: string;
  referenceImage?: {
    base64: string;
    mimeType: string;
  };
}

export interface EmployeeTestimony {
  id: string;
  employeeId: string;
  employeeName: string;
  testimony: string;
  contextSummary?: string;
  isSaved?: boolean;
}

// Unified multi-file analysis "case"
export interface EvidenceCase {
  id: string;
  name: string; // e.g., "<file1> + <file2> + ..."
  fileIds: string[];
  status: EvidenceStatus;
  analysis?: AnalysisResult;
  recognitionVerified?: boolean;
  analysisDocumentFileName?: string; // Saved report file name (for download)
  analysisDocumentPath?: string; // Relative path returned by server
}
